### ISSUE TITLE
cannot install this package

### ISSUE THREAD

**Issue by apolishch** [eBay/skin#2]
```
npm install --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/Cellar/node/7.5.0/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose' ]
npm info using npm@4.3.0
npm info using node@v7.5.0
npm verb request uri https://registry.npmjs.org/skin-ebay
npm verb request no auth needed
npm info attempt registry request try #1 at 1:19:56 PM
npm verb request id c5a0191f263a2661
npm verb etag W/"56c51db3-1ac"
npm verb lastModified Thu, 18 Feb 2016 01:26:11 GMT
npm http request GET https://registry.npmjs.org/skin-ebay
npm http 304 https://registry.npmjs.org/skin-ebay
npm verb headers { date: 'Wed, 01 Mar 2017 13:19:46 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: 'W/"56c51db3-1ac"',
npm verb headers   age: '0',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-den6023-DEN',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1488374386.625591,VS0,VE52',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/skin-ebay from cache
npm verb get saving skin-ebay to /Users/abe/.npm/registry.npmjs.org/skin-ebay/.cache.json
npm verb correctMkdir /Users/abe/.npm correctMkdir not in flight; initializing
npm verb stack TypeError: Cannot convert undefined or null to object
npm verb stack     at Function.keys (<anonymous>)
npm verb stack     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:126:29)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm verb stack     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
npm verb stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:261:18
npm verb stack     at FSReqWrap.oncomplete (fs.js:112:15)
npm verb cwd /Users/abe/github/ebay/GSUI/applications/shippinglabels
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "install" "--verbose"
npm ERR! node v7.5.0
npm ERR! npm  v4.3.0

npm ERR! Cannot convert undefined or null to object
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/abe/.npm/_logs/2017-03-01T13_19_57_259Z-debug.log
```

**Comment by apolishch** [comment]
o my bad makes me feel stupid...

Going to close this until then.
